### ISSUE TITLE
error while broken django-mailbox install

### ISSUE THREAD

**Issue by zainali95** [coddingtonbear/django-mailbox#160]
```
$ python3 manage.py migrate

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib64/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib64/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib64/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 453, in <module>
    class Message(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 457, in Message
    verbose_name=_(u'Mailbox'),
TypeError: __init__() missing 1 required positional argument: 'on_delete'
[ec2-user@ip-172-31-39-212 hirewiz]$ python3 manage.py makemagrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib64/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib64/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib64/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 453, in <module>
    class Message(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 457, in Message
    verbose_name=_(u'Mailbox'),
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by ad-m** [comment]
Django>2.x incompatibility. I made a new release within 7 days from now.

Workaround: '''pip install 'Django<2.0' '''

**Comment by soppliger** [comment]
My entire app is written in 2.0, so downgrading isn't an option for me. I resolved the issue by manually adding on_delete to the models. I also had to manually edit the the 0001_initial.py migration to include the on_delete. Once I did that, the migrations ran successfully and the app now works correctly with Django 2.0. 

In my case the path to the django_mailbox models is: 
~/dev/.virtualenvs/df/lib/python3.6/site-packages/django_mailbox/models.py

There are 3 places to add the on_delete method as follows:

```
class Message(models.Model):
    mailbox = models.ForeignKey(
        Mailbox,
        related_name='messages',
        verbose_name=_(u'Mailbox'),
        on_delete=models.CASCADE,
    )

in_reply_to = models.ForeignKey(
        'django_mailbox.Message',
        related_name='replies',
        blank=True,
        null=True,
        verbose_name=_(u'In reply to'),
        on_delete=models.PROTECT,
    )

class MessageAttachment(models.Model):
    message = models.ForeignKey(
        Message,
        related_name='attachments',
        null=True,
        blank=True,
        verbose_name=_('Message'),
        on_delete=models.PROTECT,
    )
```

The migration file is in the same path under ...django_mailbox/migrations/0001_initial.py

Add on_delete to 'in_reply_to', 'mailbox', and 'message' as follows:

```
('in_reply_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', verbose_name='In reply to', blank=True, to='django_mailbox.Message', null=True)),
('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', verbose_name='Mailbox', to='django_mailbox.Mailbox')),
('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', verbose_name='Message', blank=True, to='django_mailbox.Message', null=True)),
```

**Comment by ad-m** [comment]
There is required changes in repository (see https://github.com/coddingtonbear/django-mailbox/commit/725229560162322af96f5e374bda40db30584669 ). Unfortunatly, it wasn't released yet by @coddingtonbear. I don't have priviledges on pypi & there is no CD.

If you want you can use:
```pip install git+https://github.com/coddingtonbear/django-mailbox.git@725229560162322af96f5e374bda40db30584669```
You can put it in requirements.txt too.

**Comment by coddingtonbear** [comment]
I'll have a look at pulling together a release in the next day or so; sorry, folks, I've been on vacation for the last couple of weeks!

**Comment by coddingtonbear** [comment]
Released v 4.7.0 just a little while back (via dfad0f8f9c29f1474687ab7180abc2c6fa2ca97c).  Let me know if if that doesn't solve this, please.

**Comment by coddingtonbear** [comment]
I'm _assuming_ that this solves this problem, but don't have the time at the moment to verify personally. Please let me know if this is still an issue!
